---
title: "p8105_hw3_gwk2111"
author: "Zach Keefer"
date: "10/11/2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(p8105.datasets)
```

##Problem 1

```{r}
brfss_data = brfss_smart2010 %>% 
  janitor::clean_names() %>%
  filter(topic == "Overall Health") %>% 
  mutate(response = factor(response, levels = c("Excellent", "Very good", "Good", "Fair", "Poor"), ordered = TRUE))
```

```{r}
filter(brfss_data, year == 2002) %>% 
  group_by(locationabbr) %>% 
  summarise(location_freq = n_distinct(geo_location)) %>% 
  filter(location_freq == 7)
```

```{r}
group_by(brfss_data, locationabbr, year) %>% 
  summarise(location_freq = n_distinct(geo_location)) %>%  
   ggplot(aes(x = year, y = location_freq)) +
       geom_line(aes(color = locationabbr))   
```

```{r}
filter(brfss_data, year == 2002 | year == 2006 | year == 2010, locationabbr == "NY") %>% 
  spread(key = response, value = data_value) %>% 
  group_by(year) %>% 
  summarize(mean_proportion = mean(Excellent, na.rm = TRUE),
            sd = sd(Excellent, na.rm = TRUE)) %>% 
  knitr::kable(digits = 3)
```

```{r}
spread(brfss_data, key = response, value = data_value) %>% 
  janitor::clean_names() %>% 
  group_by(locationabbr, year) %>% 
  summarize(mean_excellent = mean(excellent, na.rm = TRUE),
         mean_very_good = mean(very_good, na.rm = TRUE),
         mean_good = mean(good, na.rm = TRUE),
         mean_fair = mean(fair, na.rm = TRUE),
         mean_poor = mean(poor, na.rm = TRUE)) %>%
  gather(key = response, value = mean, mean_excellent:mean_poor) %>% 
  ggplot(aes(x = year, y = mean)) +
  geom_line(aes(color = locationabbr)) +
  facet_grid(~response)
```


##Problem 2

```{r}
instacart = instacart %>% 
  janitor::clean_names()
```

```{r}
count(instacart, aisle_id) %>% 
  nrow()

count(instacart, aisle_id) %>% 
  filter(min_rank(desc(n)) < 2)
```

```{r}
group_by(instacart, aisle) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = aisle, y = n)) +
  geom_bar(stat = "identity") 
```

```{r}
filter(instacart, aisle == "baking ingredients" | aisle == "dog food care" | aisle == "packaged vegetables fruits") %>% 
  group_by(aisle, product_name) %>% 
  summarize(most_popular = n()) %>%
  filter(min_rank(desc(most_popular)) < 2) %>% 
  knitr::kable()
```

```{r}
library(lubridate)
filter(instacart, product_name == "Pink Lady Apples" | product_name == "Coffee Ice Cream") %>% 
  mutate(order_dow = order_dow + 1) %>% 
  mutate(day = wday(order_dow, label = TRUE)) %>% 
  group_by(day, product_name) %>%
  summarise(mean_hour = mean(order_hour_of_day)) %>% 
  spread(key = product_name, value = mean_hour) %>% 
  knitr::kable()
  
```


##Problem 3

```{r}
ny_noaa = ny_noaa %>% 
  janitor::clean_names()
```

```{r}
ny_noaa = ny_noaa %>% 
  mutate(year = year(date),
       month = month(date, label = TRUE),
       day = lubridate::floor_date(date, unit = "day"),
       prcp = prcp/10,
       tmin = (as.numeric(tmin))/10,
       tmax = (as.numeric(tmax))/10) 
 
count(ny_noaa, snow) %>%
  filter(min_rank(desc(n)) < 2) 

```

```{r}
filter(ny_noaa, month == "Jan" | month == "Jul") %>% 
  group_by(month, id, year) %>% 
  summarize(mean_temp = mean(tmax, na.rm = FALSE)) %>% 
  ggplot(aes(x = year, y = mean_temp)) +
  geom_point() +
  geom_smooth() +
  facet_grid(~month)
```


```{r}
library(hexbin)
library(ggridges)
library(patchwork)
tmax_tmin_p = ggplot(ny_noaa, aes(x = tmax, y = tmin)) +
  geom_hex() 

snowfall_p = filter(ny_noaa, snow > 0 & snow < 100) %>%
  mutate(year = as.character(year)) %>% 
  ggplot(aes(x = snow, y = year)) + 
  geom_density_ridges() 

(tmax_tmin_p + snowfall_p)


```

